version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/opt/gymbackend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
